name: i dibil

on: [push, pull_request]

jobs:
  mytesting:
    runs-on: ubuntu-latest
    steps:
    - name: work with git
      uses: actions/checkout@v2

    - name: Ruby
      run: |
        sudo apt-get install ruby-full -y
        irb testfordibil/testing.rb
#        echo $(ruby -v)

#          gem install bundler
#          bundle install --jobs 4 --retry 3
#          sudo apt-get install ruby-full
#          sudo gem install bundler -v 1.17.3
#          sudo bundle install --jobs 4 --retry 3
#          bundle exec rake
#          irb fileforstudyci.rb

